import { useMemo, useState } from 'react'
import { ChevronDown, ChevronRight } from 'lucide-react'
import type { BacklogReportRow } from '@/domain/models/report'
import { formatPrice } from '@/utils/format'

export const pivotMeasures = [{ key: 'backlogStart', label: 'Backlog Start' }, { key: 'nob', label: 'NOB' }, { key: 'revenue', label: 'Revenue' }, { key: 'backlogEnd', label: 'Backlog End' }] as const
export type PivotMeasureKey = typeof pivotMeasures[number]['key']
export interface PivotTableProps { data: BacklogReportRow[]; rows: string[]; columns: string[]; values: PivotMeasureKey[] }

type Node = { key: string; parent: string; depth: number; values: string[]; rows: BacklogReportRow[]; children: boolean }
type ColumnLeaf = { key: string; values: string[]; rows: BacklogReportRow[] }
type ColumnNode = { key: string; label: string; children: ColumnNode[]; leafCount: number }

export function PivotTable({ data, rows: rowFields, columns: columnFields, values }: PivotTableProps) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const model = useMemo(() => makeModel(data, rowFields, columnFields), [data, rowFields, columnFields])
  const visible = model.rowNodes.filter((node) => { let parent = node.parent; while (parent) { if (!expanded.has(parent)) return false; parent = model.nodeByKey.get(parent)?.parent ?? '' } return true })
  const toggle = (key: string) => setExpanded((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next })
  return <div className="max-h-[520px] overflow-auto rounded border border-border/60"><table className="min-w-max border-collapse text-xs"><thead className="sticky top-0 z-20"><PivotHeaders tree={model.columnTree} leaves={model.leaves} rowDepth={rowFields.length} columnDepth={columnFields.length} values={values} /></thead><tbody>{visible.map((node) => <tr key={node.key} className={node.children ? 'bg-surface-muted font-semibold' : 'bg-surface'}>{rowFields.map((field, index) => <td key={field} className="border-b border-border/60 px-2 py-1.5" style={{ paddingLeft: index === node.depth ? `${8 + node.depth * 16}px` : undefined }}>{index === node.depth ? <>{node.children ? <button aria-label={`${expanded.has(node.key) ? 'Collapse' : 'Expand'} ${node.values[index]}`} onClick={() => toggle(node.key)} className="mr-1 align-middle">{expanded.has(node.key) ? <ChevronDown className="inline size-3" /> : <ChevronRight className="inline size-3" />}</button> : <span className="mr-1 inline-block size-3" />}{node.values[index]}</> : node.depth === rowFields.length - 1 ? node.values[index] : ''}</td>)}{model.leaves.flatMap((leaf) => values.map((key) => { const measure = pivotMeasures.find((candidate) => candidate.key === key)!; return <td key={`${leaf.key}-${measure.key}`} className="border-b border-border/60 px-2 py-1.5 text-right tabular-nums">{formatPrice(sumMeasure(node.rows.filter((row) => matches(row, leaf.values, columnFields)), measure.key))}</td> }))}</tr>)}<tr className="border-t-2 border-border-strong bg-primary-muted font-bold"><td colSpan={Math.max(1, rowFields.length)} className="sticky left-0 z-10 px-2 py-1.5">Grand Total</td>{model.leaves.flatMap((leaf) => values.map((key) => <td key={`${leaf.key}-${key}`} className="px-2 py-1.5 text-right tabular-nums">{formatPrice(sumMeasure(data.filter((row) => matches(row, leaf.values, columnFields)), key))}</td>))}</tr></tbody></table></div>
}

function makeModel(data: BacklogReportRow[], rowFields: string[], columnFields: string[]) { const nodes = new Map<string, Node>(); for (const row of data) for (let depth = 0; depth < rowFields.length; depth++) { const values = rowFields.slice(0, depth + 1).map((field) => String((row as unknown as Record<string, unknown>)[field] ?? '—')); const key = values.join('|'); const parent = values.slice(0, -1).join('|'); const existing = nodes.get(key); if (existing) existing.rows.push(row); else nodes.set(key, { key, parent, depth, values, rows: [row], children: false }) } for (const node of nodes.values()) if (node.parent) nodes.get(node.parent)!.children = true; if (rowFields.length === 0) nodes.set('all', { key: 'all', parent: '', depth: 0, values: [], rows: data, children: false }); const leaves = new Map<string, ColumnLeaf>(); if (columnFields.length === 0) leaves.set('all', { key: 'all', values: [], rows: data }); else for (const row of data) { const values = columnFields.map((field) => String((row as unknown as Record<string, unknown>)[field] ?? '—')); const key = values.join('|'); const existing = leaves.get(key); if (existing) existing.rows.push(row); else leaves.set(key, { key, values, rows: [row] }) } return { rowNodes: [...nodes.values()], nodeByKey: nodes, leaves: [...leaves.values()], columnTree: buildColumnTree([...leaves.values()], columnFields.length) } }
function buildColumnTree(leaves: ColumnLeaf[], depth: number): ColumnNode[] { if (depth === 0) return []; const roots: ColumnNode[] = []; for (const leaf of leaves) { let level = roots; for (let index = 0; index < leaf.values.length; index += 1) { const value = leaf.values[index]; let node = level.find((candidate) => candidate.label === value); if (!node) { node = { key: leaf.values.slice(0, index + 1).join('|'), label: value, children: [], leafCount: 0 }; level.push(node) } node.leafCount += 1; level = node.children } } return roots }
function PivotHeaders({ tree, leaves, rowDepth, columnDepth, values }: { tree: ColumnNode[]; leaves: ColumnLeaf[]; rowDepth: number; columnDepth: number; values: PivotMeasureKey[] }) { if (columnDepth === 0) return <tr><th colSpan={Math.max(1, rowDepth)} className="sticky left-0 z-30 border border-border bg-surface-muted px-2 py-1.5 text-left">Row Labels</th>{values.map((key) => <th key={key} className="border border-border bg-surface-muted px-2 py-1.5 text-right font-semibold">{pivotMeasures.find((measure) => measure.key === key)?.label}</th>)}</tr>; const rows = []; for (let level = 0; level < columnDepth; level += 1) rows.push(<tr key={level}>{level === 0 && <th colSpan={Math.max(1, rowDepth)} rowSpan={columnDepth + 1} className="sticky left-0 z-30 border border-border bg-surface-muted px-2 py-1 text-left">Row Labels</th>}{nodesAtLevel(tree, level).map((node) => <th key={node.key} colSpan={node.leafCount * values.length} className="border border-border bg-surface-muted px-2 py-1 text-center font-semibold">{node.label}</th>)}</tr>); rows.push(<tr key="measures">{leaves.flatMap((leaf) => values.map((key) => <th key={`${leaf.key}-${key}`} className="border border-border bg-surface-muted px-2 py-1 text-right font-semibold">{pivotMeasures.find((measure) => measure.key === key)?.label}</th>))}</tr>); return rows }
function nodesAtLevel(nodes: ColumnNode[], level: number): ColumnNode[] { if (level === 0) return nodes; return nodes.flatMap((node) => nodesAtLevel(node.children, level - 1)) }
function matches(row: BacklogReportRow, values: string[], fields: string[]) { return fields.every((field, index) => String((row as unknown as Record<string, unknown>)[field] ?? '—') === values[index]) }
function sumMeasure(rows: BacklogReportRow[], key: PivotMeasureKey) { return rows.reduce((sum, row) => sum + row[key], 0) }
